version: "3.8" # Using a later version to support the 'deploy' and 'device_requests' options

services:
  app:
    image: registry.gitlab.com/phuctran2703/owlv2_project
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
